// public/react-components/components/select/src/selectMultiple.jsx
import React from 'react';
import PropTypes from "prop-types";
import Component from '../../Base/index';
import clickoutside from '../../../src/utils/clickoutside';
import Tag from '../../tag/index';

const KEYCODE = {
  ENTER: 13,
  ESC: 27
};

class SelectMultiple extends Component {

  constructor(props) {

    super(props);

    this.state = {
      showLabel: [],
      showValue: this.props.value,
      isShowPopper: false,
    };

    this.params = {
      popperHandler: null,
    };

    this.ref = {
      root: React.createRef(),
      input: React.createRef(),
      popper: React.createRef(),
      popperContent: React.createRef()
    };
  }

  static getDerivedStateFromProps(props, state) {

    if (props.value !== state.prevPropsValue) {
      return {
        prevPropsValue: props.value,
        showLabel: [...props.value],
      };
    }

    return null;
  }

  componentDidMount() {

    clickoutside.bind(this.ref.root.current, sign => sign && this.hidePopper());

    this.params.popperHandler = new Popper(
      this.ref.root.current,
      this.ref.popper.current,
      {
        updateImmediately: false,
        placement: 'bottom-start',
        modifiers: {
          // 设置输入框和弹层之间的距离
          offset: {
            offset: [0, 10]
          }
        }
      }
    );

    this.params.popperHandler.hide();
  }

  componentWillUnmount() {
    clickoutside.unbind(this.ref.root.current);
    this.params.popperHandler.destroy();
  }

  // 打开popper
  showPopper() {

    this.ref.popperContent.current.scrollTop = 0;
    this.params.popperHandler.show();

    this.setState({
      isShowPopper: true
    });
  }

  // 隐藏popper
  hidePopper() {

    this.params.popperHandler.hide();
    this.ref.input.current && this.ref.input.current.blur();

    this.setState({
      isShowPopper: false
    });
  }

  // 更新popper位置
  updatePopper() {
    this.params.popperHandler.update();
  }

  // 设置 showValue
  setSelectedValue(value) {

    let showValue = this.state.showValue;
    showValue.includes(value) ? showValue.splice(showValue.indexOf(value), 1) : showValue.push(value);

    this.setState({
      showValue: showValue
    });
  }

  // 设置 showLabel
  setSelectedLabel(value) {

    let showLabel = this.state.showLabel;
    showLabel.includes(value) ? showLabel.splice(showLabel.indexOf(value), 1) : showLabel.push(value);

    this.setState(
      {showLabel: showLabel},
      _ => {
        this.updatePopper();
      }
    );
  }

  // 点击option item的关闭
  onCloseItem(event, index) {

    // 阻止事件执行
    event.nativeEvent.stopImmediatePropagation();

    // 更改子节点监控的数据，触发子节点更新showLabel数据
    this.state.showValue.splice(index, 1);
    this.state.showLabel.splice(index, 1);
    this.setState(
      {
        showValue: this.state.showValue,
        showLabel: this.state.showLabel
      },
      _ => {
        this.updatePopper();
      }
    );

    this.props.onClose && this.props.onClose(this.state.showLabel);
  }

  // 点击option的item
  onClickOption(value, label, event) {
    this.props.onClickOption && this.props.onClickOption(this.state.showLabel);
  }

  // 输入框点击事件处理
  onInputClick() {
    this.showPopper();
  }

  // keydown事件处理
  onKeyDown(event) {
    switch (event.keyCode) {
      case KEYCODE.ENTER:
        this.params.popperHandler.toggle();
        break;
      case KEYCODE.ESC:
        this.hidePopper();
        break;
    }
  }

  // 获得input展示内容
  renderInputContent() {

    let tagHeight = this.props.minHeight - 10 - 2;

    return this.state.showLabel.length > 0 ?
      this.state.showLabel.map(
        (item, index) => React.cloneElement(
          <Tag/>,
          {
            key: (new Date()).getTime() + index,
            isCloseable: true,
            childValue: String(item),
            height: tagHeight,
            onClose: event => this.onCloseItem.bind(this)(event, index),
          }
        )
      ) :
      <span className="v-self-placeholder" style={{lineHeight: `${tagHeight}px`}}>
        {this.props.placeholder}
      </span>;
  }

  // 获得popper展示内容
  renderPopperContent() {

    return React.Children.map(
      this.props.children,
      item => {

        if (!React.isValidElement(item) || item.type.elementName !== 'Option') {
          return null;
        }

        return React.cloneElement(
          item,
          {
            parent: {
              isSingle: false,
              showValue: this.state.showValue,
              setSelectedValue: this.setSelectedValue.bind(this),
              setSelectedLabel: this.setSelectedLabel.bind(this),
              onClickOption: this.onClickOption.bind(this),
            }
          }
        )
      }
    )
  }

  render() {

    return (
      <div
        ref={this.ref.root}
        className={this.className('v-select')}
        style={this.style()}
        onKeyDown={this.onKeyDown.bind(this)}
      >
        <div
          ref={this.ref.input}
          className="v-multiple-reference v-hover-show-scrollbar"
          style={{
            width: `${this.props.width}px`,
            minHeight: `${this.props.minHeight}px`,
            maxHeight: `${this.props.maxHeight}px`
          }}
          onClick={this.onInputClick.bind(this)}
          tabIndex={1}
        >
          {this.renderInputContent()}
          <span className="v-select-direction">
            <i className={`iconfont icon-down ${this.state.isShowPopper && 'v-up' || ''}`}/>
          </span>
        </div>

        <div
          ref={this.ref.popper}
          className="v-popper"
        >
          <ul ref={this.ref.popperContent} className="v-popper-content v-hover-show-scrollbar">
            {this.renderPopperContent()}
          </ul>

          <div className="v-popper-arrow"/>
        </div>
      </div>
    );
  }
}

SelectMultiple.defaultProps = {
  width: 180,
  minHeight: 40,
  maxHeight: 200,
  value: [],
  placeholder: '请选择',
};

SelectMultiple.propTypes = {
  width: PropTypes.number,       // 宽度
  minHeight: PropTypes.number,   // 最大高度
  maxHeight: PropTypes.number,   // 最小高度
  value: PropTypes.array,        // 展示的值
  placeholder: PropTypes.string, // 默认值

  onClickOption: PropTypes.func, // 点击option的item
  onCloseItem: PropTypes.func,   // 点击option的关闭
};

export default SelectMultiple;

// public/vue-components/components/select/src/select-multiple.vue
<template>

    <div
        class="v-select"
        v-click-outside="clickOutside"
    >
        <div
            class="v-multiple-reference v-hover-show-scrollbar"
            ref="reference"
            @click="clickInputLike"
            :style="{
                width: `${width}px`,
                minHeight: `${minHeight}px`,
                maxHeight: `${maxHeight}px`
            }"
            tabIndex="1"
        >

            <template v-if="showLabel.length > 0">
                <v-tag
                    v-for="(value,index) in showLabel"
                    @close="closeItem($event, index)"
                    :height="minHeight-10-2"
                    :key="index"
                    closeable
                >
                    {{value}}
                </v-tag>
            </template>
            <template v-else>
                <span class="v-self-placeholder" :style="{lineHeight:`${minHeight-10-2}px`}">
                    {{placeholder}}
                </span>
            </template>

            <span class="select-direction">
                <i class="iconfont icon-down" :class="isShowPopper&&'up'"></i>
            </span>
        </div>

        <div
            v-show="isShowPopper"
            ref="popper"
            class="v-popper"
        >

            <ul class="v-popper-content v-hover-show-scrollbar">

                <slot></slot>
            </ul>

            <div class="v-popper-arrow"></div>
        </div>

    </div>
</template>

<script>

  import clickOutside from "../../../src/directives/clickoutside"
  import vTag from "../../tag/index";

  export default {

    name: "v-select-multiple",

    inheritAttrs: false,

    directives: {
      clickOutside
    },

    components: {
      vTag
    },

    props: {

      width: {
        required: false,
        type: Number,
        default: 180
      },
      minHeight: {
        required: false,
        type: Number,
        default: 40
      },
      maxHeight: {
        required: false,
        type: Number,
        default: 200
      },
      value: {
        required: false,
        default: []
      },
      placeholder: {
        required: false,
        default: '请选择'
      },
    },

    data() {
      return {
        isShowPopper: false, // 控制是否应该展示popper
        popperHandler: null, // popper组件实例化后的句柄
        showLabel: [], // 输入框展示的内容
        updateSign: {} // 子组件更新监控标识
      }
    },

    computed: {
      // item 可根据 showValue 判断当前active的值
      showValue: {
        get() {
          return this.value;
        },
        set(val) {
          this.$emit('input', val);
        },
      },
    },

    methods: {

      clickOutside(event, sign) {
        if (sign) {
          this.hidePopper();
        }
      },

      // 点击在类似搜索框的位置
      clickInputLike() {

        this.showPopper();
      },

      // 点击某个tag的关闭按钮
      closeItem(event, index) {

        event.stopPropagation();

        // 更新showValue数据
        this.showValue.splice(index, 1);
        // 更新showLabel数据
        this.showLabel = [];
        // 更改子节点监控的数据，触发子节点更新showLabel数据
        this.childrenUpdate();
      },

      triggerClick(value, label, event) {
        this.$emit('click-option', value, label, event)
      },

      // 更改子节点监控的数据，触发子节点更新showLabel数据
      childrenUpdate() {
        this.updateSign = {};
      },

      updatePopper() {
        this.popperHandler.update();
      },

      showPopper() {
        this.isShowPopper = true;
        this.popperHandler.show();
        this.selectedShow();
      },

      hidePopper() {
        this.isShowPopper = false;
        this.popperHandler.hide();
      },

      // 存在选中条目时，要让选中条目处于展示的最下方
      selectedShow() {

        // 当没有赋值的时候
        if (this.showLabel.length === 0) {
          this.$el.querySelector('.v-popper-content').scrollTop = 0;
          return;
        }

        let popper = this.$el.querySelector('.v-popper-content'),
          activeEle = popper.querySelector('.active'),
          activeEleClientRect = activeEle.getBoundingClientRect(),
          popperClientRect = popper.getBoundingClientRect(),
          itemHeight = activeEleClientRect.height,
          index = [].slice.call(popper.children).indexOf(activeEle);

        this.$el.querySelector('.v-popper-content').scrollTop =
          (index + 1) * itemHeight +
          parseFloat(getComputedStyle(popper).getPropertyValue('padding-top')) -
          popperClientRect.height;
      },
    },

    watch: {

      showLabel() {

        // 当出现滚动条的时候，让最下面的tag显示出来
        let showArea = this.$refs.reference;
        showArea.scrollTop = showArea.scrollHeight - showArea.clientHeight;

        // 需要待视图更新后，即输入框大小已经改变完成后再调用update方法
        this.$nextTick(
          _ => {
            this.updatePopper();
          }
        )
      },
    },

    mounted() {

      this.popperHandler = new Popper(
        this.$refs.reference,
        this.$refs.popper,
        {
          updateImmediately: false,
          placement: 'bottom-start',
          modifiers: {
            // 设置输入框和弹层之间的距离
            offset: {
              offset: [0, 10]
            }
          }
        }
      );
    },

    beforeDestroy() {
      this.popperHandler.destroy();
    },
  }
</script>
