// public/vue-components/components/step/src/step.vue
<template>
    <div
        class="v-step"
        :style="{
                width:!!$parent.space?`${$parent.space}px`:'auto',
                flex:!!$parent.space||isLast?'none':'1'
            }"
    >
        <div class="chart-part" ref="chart-part">
            <!--自定义图形-->
            <slot v-if="$slots.step" name="step"></slot>
            <!--默认图形,简单模式时无图形-->
            <template v-else-if="!$parent.simple">
                <template v-if="$parent.error && $parent.process===currentIndex">
                    <div class="step error">×</div>
                </template>
                <template v-else>
                    <div v-show="currentStatus===types.success" class="step success iconfont icon-caozuochenggong"></div>
                    <div v-show="currentStatus===types.process" class="step process">{{currentIndex+1}}</div>
                    <div v-show="currentStatus===types.wait" class="step wait">{{currentIndex+1}}</div>
                    <div v-show="currentStatus===types.error" class="step error">{{currentIndex+1}}</div>
                </template>
            </template>
            <!--中间的图形部分-->
            <template v-if="!isLast">
                <!--简单模式的中间内容-->
                <div v-if="$parent.simple" class="simple">></div>
                <!--默认的中间内容-->
                <div v-else class="line" :class="currentIndex<$parent.process-1&&'process'"></div>
            </template>
        </div>

        <div class="content-part" :class="currentStatus">
            <div v-if="$slots.title" class="title">
                <div class="content" :style="{transform:alignTranslate}">
                    <slot name="title"></slot>
                </div>
            </div>
            <div v-else class="title">
                <div class="content" :style="{transform:alignTranslate}">
                    {{title}}
                </div>
            </div>

            <div v-if="$slots.description" class="description">
                <div class="content" :style="{transform:alignTranslate}">
                    <slot name="description"></slot>
                </div>
            </div>
            <div v-else class="description">
                <div class="content" :style="{transform:alignTranslate}">
                    {{description}}
                </div>
            </div>
        </div>
    </div>
</template>

<script>

  import '../css/step.scss';
  import {getStyle} from "../../../src/utils/dom"

  export default {

    name: "v-step",

    props: {
      title: {
        require: false,
        type: String,
        default: '',
      },
      description: {
        require: false,
        type: String,
        default: '',
      },
      simple: {
        require: false,
        type: Boolean,
        default: false
      },
    },

    data() {
      return {

        types: {
          error: 'error',
          process: 'process',
          success: 'success',
          wait: 'wait',
        },

        currentIndex: this.$parent.$children.indexOf(this),
        isLast: false,
        alignTranslate: 0
      }
    },

    computed: {

      currentStatus() {

        let status = '';
        if (this.$parent.process === this.currentIndex && this.$parent.error) {
          status = this.types.error;
        } else if (this.$parent.process === this.currentIndex) {
          status = this.types.process;
        } else if (this.$parent.process > this.currentIndex) {
          status = this.types.success;
        } else {
          status = this.types.wait;
        }
        return status;
      }
    },

    methods: {

      setIsLast() {
        let children = this.$parent.$children;
        this.isLast = this === children[children.length - 1];
      },

      // 居中设置
      setAlignTranslate() {

        if (!this.$parent.alignCenter) {
          return this.alignTranslate = `translateX(0)`;
        }

        let child = this.$refs && this.$refs['chart-part'] && this.$refs['chart-part'].children;

        if (!child || child.length === 0) {
          return;
        }

        for (let index = 0; index < child.length; index++) {
          let item = child[index];
          if (getStyle(item, 'display') !== 'none') {
            return this.alignTranslate = `translateX(calc(-50% + ${item.clientWidth / 2}px))`;
          }
        }
      },
    },

    mounted() {

      this.setIsLast();

      this.setAlignTranslate();
    },
  }
</script>

// public/react-components/components/steps/src/step.jsx
import React from 'react';
import PropTypes from "prop-types";
import Component from '../../Base/index';

class Step extends Component {

  static elementName = 'Step';

  constructor(props) {

    super(props);

    this.params = {
      types: {
        error: 'error',
        process: 'process',
        success: 'success',
        wait: 'wait',
      },
    };

    this.ref = {
      chartPart: React.createRef()
    };
  }

  // 当前节点的状态
  currentStatus() {

    let status = '';
    if (this.props.parent.isError && this.props.parent.process === this.props.parent.currentIndex) {
      status = this.params.types.error;
    } else if (this.props.parent.process === this.props.parent.currentIndex) {
      status = this.params.types.process;
    } else if (this.props.parent.process > this.props.parent.currentIndex) {
      status = this.params.types.success;
    } else {
      status = this.params.types.wait;
    }
    return status;
  }

  render() {

    let chartPart = null, linePart = null;

    if (this.props.stepComponent) {
      chartPart = this.props.stepComponent;
    }
    else if (!this.props.parent.isSimple) {
      if (this.props.parent.isError && this.props.parent.process === this.props.parent.currentIndex) {
        chartPart = <div className="v-step-one v-error">×</div>;
      }
      else {
        switch (this.currentStatus()) {
          case this.params.types.success:
            chartPart = <div className="v-step-one v-success iconfont icon-caozuochenggong"/>;
            break;
          case this.params.types.process:
            chartPart = <div className="v-step-one v-process">{this.props.parent.currentIndex + 1}</div>;
            break;
          case this.params.types.wait:
            chartPart = <div className="v-step-one v-wait">{this.props.parent.currentIndex + 1}</div>;
            break;
          case this.params.types.error:
            chartPart = <div className="v-step-one v-error">{this.props.parent.currentIndex + 1}</div>;
            break;
        }
      }
    }

    if (!this.props.parent.isLast) {
      if (this.props.parent.isSimple) {
        linePart = <div className="v-simple">></div>;
      }
      else {
        linePart =
          <div className={`v-line ${this.props.parent.currentIndex < this.props.parent.process - 1 && 'v-process' || ''}`}/>;
      }
    }

    return (
      <div
        className={this.className('v-step')}
        style={{
          ...this.style(),
          width: this.props.parent.space && !this.props.parent.isLast ? `${this.props.parent.space}px` : 'auto',
          flex: this.props.parent.space || this.props.parent.isLast ? 'none' : '1',
        }}
      >
        <div ref={this.ref.chartPart} className="v-chart-part">
          {chartPart}
          {linePart}
        </div>

        <div className={`v-content-part v-${this.currentStatus()}`}>
          {
            this.props.titleComponent ?
              <div className="v-title">
                <div className="v-content">
                  {this.props.titleComponent}
                </div>
              </div> :
              <div className="v-title">
                <div className="v-content">
                  {this.props.titleText}
                </div>
              </div>
          }
          {
            this.props.descriptionComponent ?
              <div className="v-description">
                <div className="v-content">
                  {this.props.descriptionComponent}
                </div>
              </div> :
              <div className="v-description">
                <div className="v-content">
                  {this.props.descriptionText}
                </div>
              </div>
          }
        </div>
      </div>
    );
  }
}

Step.propTypes = {
  titleText: PropTypes.string,          // 标题文字
  descriptionText: PropTypes.string,    // 描述文字

  titleComponent: PropTypes.node,       // 标题插槽
  descriptionComponent: PropTypes.node, // 描述插槽
  stepComponent: PropTypes.node,        // 自定义步骤插槽

  parent: PropTypes.shape({           // 外层元素传入的值
    currentIndex: PropTypes.number,
    space: PropTypes.number,
    process: PropTypes.number,
    isError: PropTypes.bool,
    isSimple: PropTypes.bool,
    isLast: PropTypes.bool,
  }),
};

export default Step;
